framework:
  website: symfony.com
  version: 4.3
  
files:
  - ../.config/nginx.conf

deps:
  - nginx

environment:
  APP_ENV: prod

before_command:
  - cd /usr/src/app && mkdir -p var/log && chown www-data var/log
  - cd /usr/src/app && mkdir -p var/cache && chown www-data var/cache